name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: |
        mkdir -p output/Win-x64 output/Linux-64 output/macOS-x64 output/macOS-arm64
        GOOS=windows GOARCH=amd64 go build -o output/cf_windows_x64 ./...
        GOOS=linux GOARCH=amd64 go build -o output/cf_linux_x64 ./...
        GOOS=darwin GOARCH=amd64 go build -o output/cf_macos_x64 ./...
        GOOS=darwin GOARCH=arm64 go build -o output/cf_macos_arm64 ./...
