name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: |
        GOOS=windows GOARCH=amd64 go build -o output/Win-x64/cf-tool/cf
        GOOS=linux GOARCH=amd64 go build -o output/Linux-x64/cf-tool/cf
        GOOS=darwin GOARCH=amd64 go build -o output/macOS-x64/cf-tool/cf
        GOOS=darwin GOARCH=arm64 go build -o output/macOS-arm64/cf-tool/cf
